name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.0.25
        ports:
          - 5000:27017
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      #- name: get mongodb
      #  run: |
      #    echo "docker pull mongo"
      #    docker pull mongo
      #- name: start mongodb
      #  run: |
      #    echo "docker run --name mongo -d -p 5000:27017 mongo"
      #    docker run --name mongo -d -p 5000:27017 mongo
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Integration Tests
        run: dotnet test --no-build --verbosity normal
        env:
          Database__MyConnectionString: "mongodb://localhost:5000"
